git clone https://github.com/ujwalmahule/stock-market-ui.git
git clone https://github.com/ujwalmahule/stock-market-service.git
git clone https://github.com/ujwalmahule/stock-market-upload-service.git
git clone https://github.com/ujwalmahule/stock-market-user-service.git
git clone https://github.com/ujwalmahule/config-server.git
git clone https://github.com/ujwalmahule/stock-market-config.git
git clone https://github.com/ujwalmahule/stock-market-discovery-service.git
git clone https://github.com/ujwalmahule/stock-market-file-processing-service.git
git clone https://github.com/ujwalmahule/stock-market-apigateway.git